dist: trusty
language: python
compiler: gcc

python:
  - "3.6"
before_install:
  - sudo apt-get install gfortran
install:
  - pip install codecov pytest-cov
script:
  - travis_wait 50 pytest --cov=./
after_success:
  - codecov