dist: xenial
language: python
python:
  - "3.7"

before_install:
  - sudo apt-get install gfortran
install:
  - pip install -r requirements.txt
  - pip install codecov pytest-cov
script:
  - pytest --cov=./

after_success:
  - codecov
