dist: xenial
language: python
python:
  - "3.7"

services:
  - docker

before_install:
  - sudo apt-get install gfortran
install:
  - pip install -r requirements.txt
  - pip install codecov pytest-cov
script:
  - travis_wait 50 pytest --cov=./

after_success:
  - codecov

deploy:
  provider: script
  script: bash docker/deploy.sh
#  on:
#      branch: master