version: 1
jobs:
  build:
    docker:
      - image: ubuntu:18.04
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build and push Docker image
          command: |
            bash docker/deploy.sh