name: Docker Image CI

on:
  push:
    branches:
      - master
  # Cron job
  # https://help.github.com/en/actions/automating-your-workflow-with-github-actions/events-that-trigger-workflows#scheduled-events-schedule
  schedule:
    # https://crontab.guru/#0_0_1_*_*
    - cron: '0 0 1 * *'

jobs:
  build-docker:
    runs-on: ubuntu-latest

    steps:
    #
    - uses: actions/checkout@v1
    - name: Build and publish the docker image
      # Environment variables set in the github secrets page
      env:
        DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: ./docker/deploy.sh
